export const ROL_ADMIN_OC = 'SCE.ADMIN.OC';
export const ROL_CAPTURA_JD = 'SCE.CAPTURA.JD';
export const ROL_CAPTURA_JL = 'SCE.CAPTURA.JL';
export const ROL_CAPTURA_OC = 'SCE.CAPTURA.oc';
export const ROL_CAPTURA_CONSEJERO_JL = 'SCE.CAPTURA_CONSEJERO.JL';
export const ROL_CAPTURA_VE_JD = 'SCE.CAPTURA_VE.JD';
export const ROL_CAPTURA_VE_JL = 'SCE.CAPTURA_VE.JL';
export const ROL_CAPTURA_VECEYEC_JD = 'SCE.CAPTURA_VCEYEC.JD';
export const ROL_CAPTURA_VECEYEC_JL = 'SCE.CAPTURA_VCEYEC.JL';
export const ROL_CAPTURA_VERFE_JD = 'SCE.CAPTURA_VERFE.JD';
export const ROL_CAPTURA_VERFE_JL = 'SCE.CAPTURA_VERFE.JL';
export const ROL_CAPTURA_VOE_JD = 'SCE.CAPTURA_VOE.JD';
export const ROL_CAPTURA_VOE_JL = 'SCE.CAPTURA_VOE.JL';
export const ROL_CAPTURA_VS_JD = 'SCE.CAPTURA_VS.JD';
export const ROL_CAPTURA_VS_JL = 'SCE.CAPTURA_VS.JL';
export const ROL_CAU_OC = 'SCE.CAU.OC';
export const ROL_CONSEJERO_JD = 'SCE.CONSEJERO.JD';
export const ROL_CONSULTA_JD = 'SCE.CONSULTA.JD';
export const ROL_CONSULTA_JL = 'SCE.CONSULTA.JL';
export const ROL_CONSULTA_OC = 'SCE.CONSULTA.OC';
export const ROL_CONSULTA_RESTRINGIDA_JD = 'SCE.CONSULTA_RESTRINGIDA.JD';
export const ROL_CONSULTA_RESTRINGIDA_JL = 'SCE.CONSULTA_RESTRINGIDA.JL';
export const ROL_CONSULTA_RESTRINGIDA_OC = 'SCE.CONSULTA_RESTRINGIDA.OC';
export const ROL_CAPTURA_OPL_JL = 'SCE.CAPTURA_OPL.JL';
export const ROL_CONSULTA_OPL_JL = 'SCE.CONSULTA_.OPL.JL';
export const ROL_CAPTURA_OPL_JD = 'SCE.CAPTURA_OPL.JD';
export const ROL_CONSULTA_OPL_JD = 'SCE.CONSULTA_.OPL.JD';
export const ROL_UNICOM_OC = 'SCE.UNICOM.OC';

export const ROLES_CONSULTA_RESTRINGIDA = {
    [ROL_CONSULTA_RESTRINGIDA_JD]: true,
    [ROL_CONSULTA_RESTRINGIDA_JL]: true,
    [ROL_CONSULTA_RESTRINGIDA_OC]: true
}